name: Custom Fork Build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get built JAR file
        id: jar
        run: |
          mkdir staging
          jar_file=$(find build/libs -name "*.jar" ! -name "*-sources.jar" ! -name "*-javadoc.jar" | head -n 1)
          cp "$jar_file" staging/
          echo "jar_name=$(basename "$jar_file")" >> "$GITHUB_OUTPUT"

      - name: Upload the .jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.jar.outputs.jar_name }}
          path: staging/${{ steps.jar.outputs.jar_name }}
          compression-level: 0
